# Generated by Django 6.0.3 on 2026-03-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformingChoicesBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='project',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='InformingChoicesBackend.eventtag'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
